# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix develop .#buildkite
       --command './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 # We use the tag that triggered the pipeline here.
 # However, this requires that the tag and the release name are the same, which
 # in practice it's always the case in this repo.
 - label: Add Ventura bottle hashes to formulae
   commands:
   - mkdir -p "Ventura"
   - nix develop .#buildkite -c gh release download "v21.3-1" -D "Ventura/" -p "*ventura.bottle.tar.gz"
   - nix develop .#autorelease -c ./scripts/sync-bottle-hashes.sh "v21.3-1" "Ventura"
