# SPDX-FileCopyrightText: 2019 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: MPL-2.0

env:
  NIX_PATH: nixpkgs=https://github.com/serokell/nixpkgs/archive/master.tar.gz
  cur_date: "$(date +\"%Y%m%d%H%M\")"

steps:
 - command: nix run nixpkgs.reuse -c reuse lint
   label: reuse lint
 - command: .buildkite/check-trailing-whitespace.sh
   label: check trailing whitespace
 - command: "nix run -f https://github.com/serokell/crossref-verifier/archive/68a1f9d25b6e7835fea8299b18a3e6c61dbb2a5c.tar.gz -c crossref-verify"
   label: crossref-verify
   soft_fail: true
 - commands:
   - nix-build -A mainnet-binaries -o mainnet-binaries
   - nix-build -A babylonnet-binaries -o babylonnet-binaries
   - nix-build -A mainnet-rpm-package -o mainnet-rpm-package --arg timestamp ${cur_date}
   - nix-build -A mainnet-deb-package -o mainnet-deb-package --arg timestamp ${cur_date}
   - nix-build -A babylonnet-rpm-package -o babylonnet-rpm-package --arg timestamp ${cur_date}
   - nix-build -A babylonnet-deb-package -o babylonnet-deb-package --arg timestamp ${cur_date}
   label: build and package
   artifact_paths:
     - ./mainnet-binaries/*
     - ./babylonnet-binaries/*
     - ./mainnet-rpm-package/*
     - ./mainnet-deb-package/*
     - ./babylonnet-rpm-package/*
     - ./babylonnet-deb-package/*
