name: Build homebrew bottles
on:
  # Run when a release is tagged
  push:
    branches:
      - "krendelhoff/bottle-workflow"
permissions:
  # Restrict GITHUB_TOKEN permissions
  contents: write
  pull-requests: write
jobs:
  sync-hashes:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GNU sed
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Install coreutils for macOS # for sha256sum
        run: brew install coreutils

       # Since using the tag that triggered the pipeline isn't very resilient, we use the version
       # from the tezos-client formula, which hopefully will stay the most up-to-date.
      - id: extract-tag
        name: Extract the right version from the formula
        run: echo "tag=$(sed -n 's/^\s\+version \"\(.*\)\"/\1/p' ./Formula/tezos-client.rb)" >> $GITHUB_ENV

       # It's possible we have had to rerun the building workflow, skipping some jobs and
       # erasing the previously built bottles, so we use the release to download them all
      - name: Download Ventura bottles from the release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release download "v21.0-1" -p "*.ventura.bottle.tar.gz" -D "./Ventura"

      - name: Add bottle hashes to formulae
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./scripts/sync-bottle-hashes.sh "v21.0-1" "Ventura"
