name: Build homebrew bottles
on:
  # Run when a release is tagged
  push:
    tags:
      - "v*"
permissions:
  # Restrict GITHUB_TOKEN permissions
  contents: write
jobs:
  build-bottles:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build bottles
        run: ./scripts/build-bottles.sh

      - name: Upload bottles to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-bottles
          path: '*.bottle.*'

      - name: Add Catalina bottle hashes to formulae
        run: ./buildkite/sync-bottle-hashes.sh "${GITHUB_REF#refs/tags/}" "Catalina"

      - name: Attach bottles to the release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload "${GITHUB_REF#refs/tags/}" *.bottle.*

